sdk: "/Users/michiko/.rvm/gems/ruby-1.9.2-p180/gems/rhodes-3.1.0"
sdkversion: 3.1.0
name: demo
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator4.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.demo
  BundleURLScheme: demo
android:
  version: 2.2
wp:
  productid: 'fc27f0b0-c3e7-012e-334c-109adda7481c'
symbian:
    uid: '0xe30a1578'

extensions: ["json", "another-extension"]
